version: "3.9"

services:
  web:
    build: ./services/web
    container_name: web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - media_volume:/src/web_app/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine3.15
    container_name: db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    container_name: nginx
    volumes:
      - media_volume:/src/web_app/media
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_data_prod:
  media_volume: