version: "3.9"

services:
  web:
    build: ./services/web
    command: python -m flask run --host=0.0.0.0
    volumes:
      - ./services/web/:/src/web_app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:13-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super
      - POSTGRES_DB=pyforge
    ports:
      - "54320:5432"


volumes:
  postgres_data: